apiVersion: v1
kind: Pod
metadata:
  name: debug-ubuntu
spec:
  volumes:
    - name: workspace
      emptyDir: {}
  containers:
    - name: debug-ubuntu
      image: ubuntu:24.04
      volumeMounts:
        - name: workspace
          mountPath: /workspace
      command:
        - "sleep"
        - "604800"
      imagePullPolicy: IfNotPresent
      restartPolicy: Always
  dnsPolicy: Default